import type { QuizQuestion } from "../questions";

/** Practice Set 13 — questions 781–802 (security, identity, governance). Original questions. */
export const set13Part1: QuizQuestion[] = [
  {
    id: 781,
    category: "Security",
    question:
      "A presigned URL is generated for a PUT to an SSE-KMS encrypted object, but uploads with the URL fail even though the signer could upload. What must accompany the signing for KMS-encrypted PUTs?",
    options: [
      "The required SSE headers (algorithm and key ID) must be included in the presigned request when it is signed, not added afterward",
      "The bucket must switch to SSE-S3 for presigned uploads",
      "KMS keys cannot be used with presigned URLs",
      "The URL must be generated by the root user",
    ],
    correctAnswers: [0],
    explanation:
      "Presigned URLs sign the exact request, including headers; adding SSE headers after signing invalidates the signature, so the encryption headers must be part of the signed request. KMS works fine with presigned uploads when signed correctly.",
  },
  {
    id: 782,
    category: "Storage",
    question:
      "A Batch Operations copy job needs a manifest of three million objects. Rather than building the list by hand, which S3 feature generates the manifest automatically?",
    options: [
      "S3 Inventory reports configured in the format S3 Batch Operations consumes (CSV with specific fields)",
      "CloudTrail data events aggregated daily",
      "Athena queries exporting object lists as text",
      "Storage Lens advanced metrics export",
    ],
    correctAnswers: [0],
    explanation:
      "S3 Inventory can emit manifests directly usable by Batch Operations, providing the object list at scale without custom tooling. CloudTrail logs API calls, Athena exports require building the pipeline, and Storage Lens is aggregate metrics.",
  },
  {
    id: 783,
    category: "Security",
    question:
      "An application using the AWS Encryption SDK encrypts thousands of small items per second, and KMS call latency dominates. Which Encryption SDK component reduces repeated key provider calls?",
    options: [
      "Data key caching through a caching cryptographic materials manager (with a secure local cache and TTL)",
      "Switching to asymmetric keys for local verification",
      "Encrypting with a static key stored in the binary",
      "Calling GenerateDataKey once for all future items indefinitely",
    ],
    correctAnswers: [0],
    explanation:
      "Data key caching reuses data keys within a bounded TTL and usage count, cutting KMS round trips while keeping per-item protection. Static or indefinitely reused keys undermine the per-data-key model.",
  },
  {
    id: 784,
    category: "Security",
    question:
      "A team must choose one store for each of three needs: (1) rotated database credentials, (2) hierarchical application configuration, (3) feature flags with gradual rollout. Which pairing is correct?",
    options: [
      "Secrets Manager for credentials, Parameter Store for hierarchical configuration, AppConfig for feature flags",
      "Parameter Store for credentials, AppConfig for configuration, Secrets Manager for flags",
      "Secrets Manager for all three, since all are secrets",
      "DynamoDB custom tables for all three",
    ],
    correctAnswers: [0],
    explanation:
      "Each service targets its niche: Secrets Manager rotates credentials, Parameter Store organizes configuration hierarchies cheaply, and AppConfig deploys validated feature changes gradually. Consolidating all into one store misapplies at least two of them.",
  },
  {
    id: 785,
    category: "Security",
    question:
      "Before granting a new role to a team, an administrator wants to test exactly which API calls the role would allow or deny for given resources — without creating the role. Which IAM tool simulates this?",
    options: [
      "The IAM policy simulator (SimulateCustomPolicy / SimulatePrincipalPolicy)",
      "IAM Access Analyzer findings",
      "STS ValidateCredentials calls",
      "CloudTrail event history replay",
    ],
    correctAnswers: [0],
    explanation:
      "The policy simulator evaluates provided (or existing principal) policies against listed actions and resources, returning allow/deny decisions safely. Access Analyzer reports external access, STS has no dry-run validation, and CloudTrail looks backwards.",
  },
  {
    id: 786,
    category: "Security",
    question:
      "Bare-metal servers in a data center must call AWS APIs using short-lived credentials without storing long-lived keys — using their existing X.509 device certificates as trust anchors. Which service federates these workloads?",
    options: [
      "IAM Roles Anywhere",
      "IAM Roles for EC2",
      "Cognito identity pools",
      "IAM Identity Center",
    ],
    correctAnswers: [0],
    explanation:
      "Roles Anywhere exchanges registered X.509 device certificates for temporary role credentials via a local agent, extending IAM roles to non-AWS workloads. EC2 instance profiles only work on EC2, Cognito targets end users, and Identity Center targets workforce console access.",
  },
  {
    id: 787,
    category: "Security",
    question:
      "Tags applied at AssumeRole time must flow onward when that session assumes a second role downstream. What makes principal tags propagate through the session chain?",
    options: [
      "Marking the tags as transitive on the first role assumption",
      "Re-deriving tags from the source IP at each hop",
      "Encoding tags into the session name",
      "Session tags never leave the first session",
    ],
    correctAnswers: [0],
    explanation:
      "Transitive session tags carry through subsequent role assumptions in the chain, enabling ABAC conditions deep in multi-hop flows. Session names, IPs, and non-transitive tags do not propagate.",
  },
  {
    id: 788,
    category: "Security",
    question:
      "A WAF web ACL receives bursts of suspicious but not clearly malicious traffic — the team wants clients to prove legitimacy (solving a challenge) before proceeding rather than being blocked outright. Which WAF action fits?",
    options: [
      "The CAPTCHA or Challenge action, requiring browser-side proof before allowing the request",
      "The Allow action with logging enabled",
      "The Count action which never interferes",
      "The Block action with a custom 403 page",
    ],
    correctAnswers: [0],
    explanation:
      "CAPTCHA and Challenge actions interpose an interactive (or transparent) proof test, letting legitimate browsers proceed while stopping scripted abuse. Allow/Count observe without testing, and Block rejects outright.",
  },
  {
    id: 789,
    category: "Security",
    question:
      "Shield Advanced should trigger its protections based on the health of the protected resources — reacting to CloudWatch health alarms as attack indicators. Which Shield Advanced construct ties health signals to mitigation?",
    options: [
      "A Shield Advanced response plan (protection health-based detection using associated health checks)",
      "A WAF rate-based rule on health endpoints",
      "A Route 53 health check alone",
      "GuardDuty health findings",
    ],
    correctAnswers: [0],
    explanation:
      "Shield Advanced response plans associate CloudWatch health-based alarms with protections so that degradation triggers DDoS-aware response automatically. WAF rules, DNS checks alone, and GuardDuty don't couple health signals to volumetric mitigation.",
  },
  {
    id: 790,
    category: "Security",
    question:
      "Regulators require that encryption keys remain under the exclusive control of a key management system outside AWS's facilities, while workloads still use KMS APIs transparently. Which KMS option satisfies this?",
    options: [
      "An external key store (XKS) backed by an external key management system outside AWS",
      "A CloudHSM cluster inside AWS",
      "A customer managed KMS key with annual rotation",
      "KMS multi-Region keys",
    ],
    correctAnswers: [0],
    explanation:
      "External key stores keep key material in an external (non-AWS) key management system while exposing KMS APIs to workloads. CloudHSM is AWS-hosted hardware, and customer managed or multi-Region keys live inside KMS.",
  },
  {
    id: 791,
    category: "Compute",
    question:
      "A payment processor must run tokenization code in a hardened, isolated compute environment where even the parent EC2 instance and its operators cannot observe the data, with KMS access mediated. Which compute construct provides this enclave?",
    options: [
      "AWS Nitro Enclaves on the parent instance",
      "A separate EC2 instance in a private subnet",
      "A Fargate task with IMDS disabled",
      "A Lambda function in a dedicated account",
    ],
    correctAnswers: [0],
    explanation:
      "Nitro Enclaves create isolated VMs from the parent instance with no persistent storage, no interactive access, and restricted KMS policies (attestation-based) — built exactly for secret processing. The alternatives are ordinary compute with standard isolation.",
  },
  {
    id: 792,
    category: "Security",
    question:
      "An ACM certificate with DNS validation approaches renewal, but renewal keeps failing. What is the most common cause?",
    options: [
      "The CNAME validation record was removed or altered, so ACM cannot prove domain control for automatic renewal",
      "The certificate expired and must be purchased again",
      "ACM requires the domain registrar to be Route 53 for renewal",
      "Renewal only occurs for email-validated certificates",
    ],
    correctAnswers: [0],
    explanation:
      "Automatic renewal depends on the DNS validation records remaining in place; removing them breaks ACM's proof of control. Certificates renew (not repurchase), Route 53 is not required as registrar, and DNS-validated is the auto-renewing type.",
  },
  {
    id: 793,
    category: "Security",
    question:
      "Which flow correctly orders the security investigation pipeline across services?",
    options: [
      "GuardDuty detects a threat → Security Hub aggregates the finding → Detective investigates scope and root cause",
      "Detective detects → GuardDuty investigates → Security Hub visualizes",
      "Security Hub detects threats directly at the packet layer",
      "Config detects → Macie investigates → Detective aggregates",
    ],
    correctAnswers: [0],
    explanation:
      "GuardDuty generates threat findings, Security Hub aggregates and prioritizes them organization-wide, and Detective builds the investigation graph. The alternatives misassign detection, investigation, and aggregation roles.",
  },
  {
    id: 794,
    category: "Management & Governance",
    question:
      "Compliance requires a check that no RDS instance uses a KMS key from a different account — logic too complex for managed Config rules. How is this implemented?",
    options: [
      "A custom Config rule backed by a Lambda function evaluating the account condition",
      "A managed Config rule with a parameter override",
      "A Trusted Advisor check with weekly review",
      "A CloudWatch alarm on RDS metrics",
    ],
    correctAnswers: [0],
    explanation:
      "Custom Config rules run Lambda evaluation logic for conditions beyond managed rules, producing standard Config compliance findings. Managed rules and their parameters can't express arbitrary cross-service logic, and the other options aren't policy evaluations.",
  },
  {
    id: 795,
    category: "Management & Governance",
    question:
      "Where should day-to-day workloads never run, according to AWS Organizations best practice?",
    options: [
      "In the organization's management account",
      "In member accounts under workload OUs",
      "In the security tooling account",
      "In delegated administrator accounts for specific services",
    ],
    correctAnswers: [0],
    explanation:
      "The management account holds organization-level control and cannot be constrained by SCPs, so it should contain no workloads — isolation limits blast radius. Workload OUs, tooling accounts, and delegated admins are the correct homes for work and services.",
  },
  {
    id: 796,
    category: "Management & Governance",
    question:
      "After an administrator manually disabled a guardrail inside an account, Control Tower must flag the divergence from its baseline. Which Control Tower capability detects this?",
    options: [
      "Control Tower drift detection for OUs, guardrails, and resources",
      "CloudFormation drift detection",
      "Config aggregator compliance view",
      "Trusted Advisor checks",
    ],
    correctAnswers: [0],
    explanation:
      "Control Tower detects drift when managed resources or guardrail configurations deviate from its landing zone baseline, surfacing it on the dashboard. CloudFormation drift is stack-scoped, Config reports rule compliance, and Trusted Advisor is advisory.",
  },
  {
    id: 797,
    category: "Management & Governance",
    question:
      "Governance requires that CloudFormation refuse to create unencrypted S3 buckets before provisioning happens — a pre-provision control inside the deployment path. Which CloudFormation feature intercepts create calls with custom logic?",
    options: [
      "CloudFormation Hooks, invoking custom logic on target resource lifecycle events",
      "A stack policy denying the bucket resource",
      "A Config rule with auto-remediation deleting bad buckets",
      "A change set reviewed manually every deploy",
    ],
    correctAnswers: [0],
    explanation:
      "CloudFormation Hooks run custom logic at specified provisioning events (like before S3 bucket creation) and can fail the call, enforcing policy pre-provision. Stack policies protect existing resources, Config remediates after the fact, and change sets don't enforce automatically.",
  },
  {
    id: 798,
    category: "Management & Governance",
    question:
      "A Service Catalog product must always launch with a specific operations-approved IAM role, regardless of which team launches it. Which Service Catalog control enforces this?",
    options: [
      "A launch constraint specifying the IAM role used for provisioning",
      "A template constraint limiting instance sizes",
      "A portfolio share to the teams",
      "A tag option on the product",
    ],
    correctAnswers: [0],
    explanation:
      "Launch constraints dictate the role Service Catalog assumes to provision, standardizing permissions no matter the launcher. Template constraints limit parameter values, shares control visibility, and tag options enforce tagging.",
  },
  {
    id: 799,
    category: "Management & Governance",
    question:
      "Operational changes (scaling, patching, failovers) must flow through an approval workflow with specified approvers and change templates, auditable end to end. Which Systems Manager capability provides change management?",
    options: [
      "Systems Manager Change Manager",
      "SSM Run Command with approver parameters",
      "CloudFormation change sets",
      "AWS Service Catalog provisioning artifacts",
    ],
    correctAnswers: [0],
    explanation:
      "Change Manager adds request/approval workflows, runbooks, and audit history for operational changes. Run Command executes without approval flows, change sets are CloudFormation-scoped previews, and Service Catalog provisions products rather than managing change approvals.",
  },
  {
    id: 800,
    category: "Management & Governance",
    question:
      "An SSM Automation runbook must pause for a designated approver before executing destructive steps. Which Automation feature gates execution?",
    options: [
      "The approve action (aws:approve) pausing the automation for designated approvers",
      "A Wait state with a fixed sleep",
      "A CloudWatch alarm requiring acknowledgment",
      "Rate control steps",
    ],
    correctAnswers: [0],
    explanation:
      "The aws:approve step pauses automation until specified approvers respond (SNS-notified), then continues or aborts. Timed waits, alarms, and rate controls don't provide human approval gates.",
  },
  {
    id: 801,
    category: "Management & Governance",
    question:
      "Which two statements describe Config conformance packs? (Select TWO.)",
    options: [
      "They bundle collections of Config rules and remediation actions as a single template",
      "They deploy across accounts in an organization from one operation",
      "They replace SCPs as preventive guardrails",
      "They collect CloudTrail events into S3",
      "They are only usable in the management account",
    ],
    correctAnswers: [0, 1],
    explanation:
      "Conformance packs package rules plus remediations for organization-wide single-operation deployment. They do not act as preventive SCPs, collect CloudTrail events, or restrict themselves to the management account.",
  },
  {
    id: 802,
    category: "Management & Governance",
    question:
      "A team notices most Trusted Advisor checks return unavailable on Basic support. What determines Trusted Advisor check availability?",
    options: [
      "The support plan tier — Business, Enterprise On-Ramp, and Enterprise unlock the full check set",
      "The number of accounts in the organization",
      "Whether Config is enabled",
      "The Region the account was created in",
    ],
    correctAnswers: [0],
    explanation:
      "Trusted Advisor gates most checks behind support tiers; Basic gets a limited core set while Business and above unlock the full catalog. Organization size, Config, and account Region don't determine check availability.",
  },
];
